version: '3.8'

services:
  backend:
    build: ./flask_api
    container_name: flask_api
    ports:
      - "5050:5050"

  frontend:
    build: ./web
    container_name: web
    ports:
      - "3000:3000"
    depends_on:
      - backend

